GRIDBOUND_FIREBASE_API_KEY=AIzaSyD-_QA_4aNkxlXTrV_dXlcMvDaVuSmuB8k
GRIDBOUND_FIREBASE_APP_ID=1:1049171441092:android:a448703565a21203e86091
GRIDBOUND_FIREBASE_PROJECT_ID=gridbound-duzman46
GRIDBOUND_FIREBASE_DATABASE_URL=https://gridbound-duzman46-default-rtdb.europe-west1.firebasedatabase.app
